server:
    port: 9999

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: 123456
    redis:
        port:6379
        host:localhost
    web:
logging:
    level:
        root: INFO
        com.lantu: DEBUG

